- name: Install webserver
  ansible.builtin.apt:
    name:
      - apache2
      - php
      - php-curl
      - php-gd
      - php-mbstring
      - php-xml
      - php-xmlrpc
      - php-soap
      - php-intl
      - php-zip
      - php-mysql
      - unzip
  become: true

- name: Configure Apache2
  template:
    src: "templates/wordpress.conf"
    dest: "/etc/apache2/sites-available/000-default.conf"

- name: Restart and enable Apache2
  systemd:
    name: apache2
    state: restarted
    enabled: yes