- name: Install webserver
  ansible.builtin.apt:
    name:
      - apache2
      - php
      - php-curl
      - php-gd
      - php-mbstring
      - php-xml
      - php-xmlrpc
      - php-soap
      - php-intl
      - php-zip
  become: true
