- name: Set webserver hostname
  ansible.builtin.hostname:
    name: "blog"
  become: true

- name: Install webserver files Red Hat
  import_tasks: redhat_install_apache.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install webserver files Debian
  import_tasks: debian_install_apache.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Add WordPress files and configure apache
  import_tasks: install_wordpress.yml
