#!/bin/bash

# TODO
# - Ask for confirmation
#   - Present list of users to delete
#   - Wait for user input [y,N] before deleting

# uclean user[,user,[...]]
# This script deletes all (non-system) users not on an explicit whitelist 
# This whitelist is a single comma-separated list
# e.g. uclean realuser,blueteamfrfr,quatuam

if [[ -z "$SUDO_USER" ]]; then
  echo "This script must be run with sudo"
  exit
fi

if [[ "$#" != 1 ]]; then
  echo "This scripts requires exactly one argument"
  exit
fi

filter="$(sed 's/,/|/g' <<< "$1")"
users=$(cat /etc/passwd | awk -v filter="${filter}" -F ':' '$1 !~ filter {print $0}' | awk -F ':' '/1[0-9]{3}/{print $1}')
echo "Users to be deleted:"
echo "$users"
opt="N"
read -p "Continue? [y/N]: " opt && [[ $opt == [yY] ]] || exit 1
for user in $users; do
  echo $user
  #userdel $user
  #usermod -s /bin/nologin $user # disable user instead of deleting
done
