# Author: Jon Rodriguez
- name: Mount SMB
  vars:
    smb_share: "/smb/share"
    smb_user: "ubuntu"
    smb_password: "student"
    mount_point: "/mnt/share"
- name: Install CIFS
  ansible.builtin.package:
    name: cifs-utils
    state: present

- name: Create Mount Poin
  ansible.builtin.file:
    path: "{{mount_point}}"
    state: directory
    mode: '0755'

- name: Mount SMB folder
  ansible.posix.mount:
    src: "{{smb_share}}"
    path: "{{mount_point}}"
    fstype: cifs
    opts: "username={{smb_user}},password{{smb_password}}"
    state: mounted
