# Author: Jon Rodriguez
- name: Ensure the C:\share directory exists
  ansible.windows.win_file:
    path: "C:\\share"
    state: directory

- name: Mount SMB (Windows)
  ansible.windows.win_share:
    name: "share"
    path: "C:\\share"
    full: "Administrators"
    read: "Users"
    list: true
    description: "Public SMB"

- name: Allow SMB ports through firewall
  community.windows.win_firewall_rule:
    name: "SMB Port {{ item }}"
    localport: "{{ item }}"
    action: allow
    direction: in
    protocol: TCP
    state: present
    enabled: yes
  loop:
    - 137
    - 138
    - 139
    - 445