- name: Install ADDS
  ansible.windows.win_features:
    name: AD-Domain-Services
    state: present
    include_management_tools: true
    
- name: Install DNS
  ansible.windows.win_features:
    name: DNS
    state: present
    include_management_tools: true

- name: Deploy domain controller
  microsoft.ad.domain_controller:
    dns_domain_name: troy.cdtalpha.cyberrange.rit.edu
    domain_admin_user: Administrator
    domain_admin_password: Password123!
    safe_mode_password: Password123!
    state: domain_controller
    install_dns: true
    reboot: true
