- name: Install ADDS
  ansible.windows.win_feature:
    name: AD-Domain-Services
    state: present
    include_management_tools: true
  notify: "win_deploy_dc : Win_reboot"

- name: Install DNS
  ansible.windows.win_feature:
    name: DNS
    state: present
    include_management_tools: true

- name: Create domain
  microsoft.ad.domain:
    dns_domain_name: "troy.cdtalpha"
    safe_mode_password: Password123!
    create_dns_delegation: false
  notify: "win_deploy_dc : Win_reboot"
