- name: Install ADDS
  ansible.windows.win_feature:
    name: AD-Domain-Services
    state: present
    include_management_tools: true
  notify: "Win_reboot"

- name: Install DNS
  ansible.windows.win_feature:
    name: DNS
    state: present
    include_management_tools: true

- name: Create domain
  microsoft.ad.domain:
    dns_domain_name: "troy.cdtalpha"
    domain_netbios_name: "troy"
    safe_mode_password: Password123!
    create_dns_delegation: false
  notify: "win_deploy_dc : Win_reboot"

- name: Promote to Domain Controller
  microsoft.ad.domain_controller:
    dns_domain_name: "troy.cdtalpha"
    domain_admin_user: "Administrator@troy.cdtalpha"
    domain_admin_password: "Password123!"
    state: "domain_controller"
  notify: "win_deploy_dc : Win_reboot"

- name: Re-enable WinRM
  ansible.windows.win_service:
    name: WinRM
    start_mode: auto
