---
# PLACEHOLDER RDP ANSIBLE
- name: Set RDP hostname
  ansible.windows.win_hostname:
    name: "rdp"

- name: Enable RDP service
  ansible.windows.win_service:
    name: TermService
    state: started
    start_mode: auto

- name: Configure firewall for RDP
  ansible.windows.win_firewall_rule:
    name: "RDP"
    localport: 3389
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: true

- name: Ensure RDP users can log in
  community.windows.win_user_right:
    name: SeRemoteInteractiveLogonRight
    users:
      - "troy.cdtalpha.com\\redteam"
      - "troy.cdtalpha.com\\admin"
    action: add