---
- name: Mount SMB
#Make sure the hosts file for the Linux install of ansible contains the target Windows PC as well as the localhost registered
  hosts: all
  vars:
    smb_share: "/smb/share"
    #replace with appropriate username
    smb_user: "ubuntu"
    #replace with appropriate password
    smb_password: "student"
    mount_point: "/mnt/share"
  tasks:
    - name: Install CIFS
      ansible.builtin.package:
        name: cifs-utils
        state: present
      when: ansible_os_family != "Windows"

    - name: Create Mount Poin
      ansible.builtin.file:
        path: "{{mount_point}}"
        state: directory
        mode: '0755'
      when: ansible_os_family != "Windows"

    - name: Mount SMB folder
      ansible.posix.mount:
        src: "{{smb_share}}"
        path: "{{mount_point}}"
        fstype: cifs
        opts: "username={{smb_user}},password{{smb_password}}"
        state: mounted
      when: ansible_os_family != "Windows"

    - name: Mount SMB (Windows)
      ansible.windows.win_share:
        name: "share"
        #make a share drive on the Windows machine for it to mount to
        path: "C:\\share"
        full: "Administrators"
        read: "Users"
        list: true
        description: "Public SMB"

      when: ansible_os_family == "Windows" 

