---
# Common variables for all hosts
ansible_user: redteam
ansible_password: Password123!
ansible_connection: ssh
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

# Default credentials
users:
  - username: redteam
    password: Password123!
  - username: ajax_the_great
    password: Password123!
  - username: odysseus
    password: Password123!
  - username: agamemnon
    password: Password123!
  - username: menelaus
    password: Password123!
  - username: diomedes
    password: Password123!

# Service ports
service_ports:
  ssh: 22
  http: 80
  mysql: 3306
  smtp: 25
  ftp: 21
  rdp: 3389
  ldap: 389