- name: Ensure apt cache is updated
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Install XFCE desktop environment
  ansible.builtin.apt:
    name:
      - xfce4
      - lightdm
      - xorg
    state: present
  become: true

- name: Set LightDM as default display manager
  ansible.builtin.debconf:
    name: lightdm
    question: shared/default-x-display-manager
    value: lightdm
    vtype: select
  become: true

- name: Enable LightDM service
  ansible.builtin.systemd:
    name: lightdm
    enabled: yes
    state: started
  become: true
