---
# Author: Adam Braccia
# Email: adam@example.com
# Date: 2025-09-10
# Purpose: Create 10 Linux users, including an admin (sudo) and redteam account
# Notes:
#   - This assumes Debian/Ubuntu (uses group 'sudo').
#   - Update 'user_password' variable to a secure hash if you want pre-set passwords.
#   - To add SSH keys, place public key files and reference in 'authorized_key'.


- name: Ensure all users exist
  user:
    name: "{{ item }}"
    password: "{{ default_password | password_hash('sha512', salt) }}"
    shell: /bin/bash
    create_home: yes
    state: present
  loop: "{{ users }}"
  become: true

- name: Check if user 'ubuntu' exists
  ansible.builtin.getent:
    database: passwd
    key: ubuntu
  register: ubuntu_exists
  failed_when: false

# - name: Remove user 'ubuntu' if they exist
#   ansible.builtin.user:
#     name: ubuntu
#     state: absent
#     remove: yes
#   when: "'ubuntu' in ubuntu_exists.ansible_facts.getent_passwd"

- name: Ensure admin user is in sudo group
  user:
    name: "{{ item }}"
    groups: sudo
    append: yes
  become: true
  loop: "{{ admins }}"

- name: Apply new admin passwords
  ansible.builtin.user:
    name: "{{ item }}"
    password: "{{ admin_def_passwd | password_hash('sha512', salt) }}"
    update_password: always
    state: present
  loop: "{{ admins }}"
  become: true

- name: Generate a random numeric suffix for the flag
  set_fact:
    flag_random: "{{ lookup('password', '/dev/null length=3') }}"
  no_log: false

- name: Assemble flag content
  set_fact:
    flag_content: "TROY{GREATEST_WARRIOR_OF_TROY_{{ flag_random }}}"

- name: Create hidden .flag.txt in hector's home
  ansible.builtin.copy:
    dest: /home/hector/.flag.txt
    content: "{{ flag_content }}\n"
    owner: hector
    group: hector
    mode: '0600'
    force: false
  become: true
  register: flag_write

- name: Make flag immutable
  command: chattr +i /home/hector/.flag.txt
  become: true

- name: Show created file path and content (debug)
  ansible.builtin.debug:
    msg:
      - "wrote: /home/hector/.flag.txt"
      - "content: {{ flag_content }}"
  when: flag_write is changed