- name: Ensure standard folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop: "{{ linux_deploy_standard_folders }}"
