---
# handlers/main.yml

- name: Restart SSH service
  ansible.builtin.service:
    name: "{{ ssh_service_name | default('sshd') }}"
    state: restarted
    enabled: yes
  become: true
  listen: restart ssh

- name: wait for ssh
  ansible.builtin.wait_for:
    host: "{{ ansible_host | default(inventory_hostname) }}"
    port: "{{ ssh_port | default(22) }}"
    timeout: 30
    state: started
  delegate_to: localhost
  run_once: false
