---
- name: Service Check Playbook
  hosts: all
  gather_facts: no
  tasks:

    # Check ICMP (ping)
    - name: Check ICMP availability
      ping:
      register: icmp_check
      ignore_errors: yes
      tags:
        - icmp

    # Check SSH for Linux
    - name: Check SSH for Linux
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
      when: "'linux' in group_names and service_type == 'ssh'"
      tags:
        - ssh

    # Check MySQL for Linux
    - name: Check MySQL for Linux
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 3306
        state: started
      when: "'linux' in group_names and service_type == 'mysql'"
      tags:
        - mysql

    # Check HTTP (WordPress) for Linux
    - name: Check HTTP (WordPress) for Linux
      uri:
        url: "http://{{ inventory_hostname }}:80"
        status_code: 200
      when: "'linux' in group_names and service_type == 'wordpress'"
      tags:
        - wordpress

    # Check FTP for Linux
    - name: Check FTP for Linux
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 21
        state: started
      when: "'linux' in group_names and service_type == 'ftp'"
      tags:
        - ftp

    # Check SMTP for Linux
    - name: Check SMTP for Linux
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 25
        state: started
      when: "'linux' in group_names and service_type == 'smtp'"
      tags:
        - smtp

- name: SMB Service Check Playbook
  hosts: smb
  gather_facts: no
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_user: ansible
    ansible_password: Password123!
    ansible_winrm_server_cert_validation: ignore

  tasks:

    # Check if the SMB (LanmanServer) service is running on Windows
    - name: Check SMB service status on Windows
      ansible.windows.win_service_info:
        name: 'LanmanServer'  # LanmanServer is the service for SMB
      register: smb_service_status
      ignore_errors: true  # Continue even if the service is not found
      tags:
        - smb

    # Check if SMB service is running and report the status
    - name: Verify SMB service is running
      debug:
        msg: "SMB service (LanmanServer) is running on {{ inventory_hostname }}"
      when: smb_service_status.services is defined and smb_service_status.services[0].state == 'running'
      tags:
        - smb

    # Fail the task if SMB service is not running
    - name: Fail if SMB service is not running
      ansible.builtin.fail:
        msg: "SMB service (LanmanServer) is not running on {{ inventory_hostname }}"
      when: smb_service_status.services is defined and smb_service_status.services[0].state != 'running'
      tags:
        - smb

    ## Check SMB for Windows
    #- name: Check SMB for Windows
    #  wait_for:
    #    host: 10.1.0.19
    #    port: 139
    #    state: started
    #    timeoute: 10
    #  #when: "'windows' in group_names and service_type == 'samba'"
    #  tags:
    #    - samba

    ## Check RDP for Windows
    #- name: Check RDP for Windows
    #  wait_for:
    #    host: 10.1.0.17
    #    port: 3389
    #    state: started
    #    timeout: 10
    #  #when: "'windows' in group_names and service_type == 'rdp'"
    #  tags:
    #    - rdp
    
    ## Check DC for Windows
    #- name: Check DC for Windows
    #  wait_for:
    #    host: 10.1.0.18
    #    port: 389
    #    state: started
    #    timeout: 10
    #  #when: "'windows' in group_names and service_type == 'dc'"
    #  tags:
    #    - dc