---
- name: Verify SMB Share Accessibility (State Check)
  hosts: smb
  gather_facts: yes

  tasks:
    - name: Check if SMB v1 is enabled
      ansible.windows.win_powershell:
        script: |
          Get-SmbServerConfiguration
      register: smbcheck 