---
- name: Verify SMB Share Accessibility
  hosts: smb
  gather_facts: yes

  tasks:
    - name: Check if SMB share is accessible
      win_command: |
        $share = '\\\\{{ ansible_host }}\\share'
        try {
          $null = New-PSDrive -Name test -PSProvider FileSystem -Root $share -Persist
          Write-Host "SMB share is accessible."
          exit 0
        } catch {
          Write-Host "SMB share is not accessible."
          exit 1
        }
      register: smb_access_check
      ignore_errors: yes
      failed_when: false
      changed_when: false

    - name: Set SMB Share Accessibility Score
      set_fact:
        smb_access_score: "{{ smb_access_check.rc | default(1) }}"

    - name: Show SMB share accessibility score
      debug:
        msg: "The SMB share accessibility score is {{ smb_access_score }}"

    - name: Fail if SMB share is not accessible
      fail:
        msg: "The SMB share is not accessible!"
      when: smb_access_score != 0
