---
- hosts: linux
  roles:
    - sys_update
  tags:
    - linux

- hosts: blog
  roles:
    - install_wordpress
  tags:
    - linux
    - blog

- hosts: database
  roles:
    - install_mysql
  tags:
    - linux
    - database

- hosts: dc
  roles:
    - win_deploy_dc
  tags:
    - windows
    - win_dc

- hosts: rdp,smb
  roles:
    - win_join_domain
  tags:
    - windows
    - win_members