---
- hosts: linux
  roles:
    - sys_update
    - linux_deploy
  tags:
    - linux

- hosts: blog
  roles:
    - install_wordpress
  tags:
    - linux
    - linux_blog

- hosts: database
  roles:
    - install_mysql
  tags:
    - linux
    - linux_database

- hosts: dc
  roles:
    - win_deploy_dc
  tags:
    - windows
    - win_dc

- hosts: ssh
  roles:
    - linux_deploy_ssh
  tags:
    - linux
    - linux_ssh

- hosts: rdp,smb
  roles:
    - win_join_domain
  tags:
    - windows
    - win_members

- hosts: smb
  roles:
    - win_smb
  tags:
    - windows
    - win_smb