---
- hosts: linux
  roles:
    - sys_update
    - linux_deploy
  tags:
    - linux

- hosts: smtp
  roles: 
    - linux_deploy_smtp
  tags:
    - linux
    - smtp

- hosts: blog
  roles:
    - install_wordpress
  tags:
    - linux
    - blog

- hosts: database
  roles:
    - install_mysql

- name: Deploy ftp
  hosts: ftp_servers
  become: yes
  vars:
    ftp_port: 21
    anonymous_root: /srv/ftp/pub
    local_users: 
      - { username: "admin", password: "admin123" }
      - { username: "user", password: "password123" }
      - { username: "ftpadmin", password: "Ftp@2024" }
    weak_password_users:
      - { username: "test", password: "test" }
      - { username: "guest", password: "guest" }
  roles:
    - ftp
  tags:
    - linux
    - database

- hosts: dc
  roles:
    - win_deploy_dc
  tags:
    - windows
    - dc

- hosts: ssh
  roles:
    - linux_deploy_ssh
  tags:
    - linux
    - ssh

- hosts: rdp,smb
  roles:
    - win_join_domain
  tags:
    - windows
    - members

- hosts: smb
  roles:
    - win_smb
  tags:
    - windows
    - smb
