---
- hosts: linux
  roles:
    - sys_update

- hosts: blog
  roles:
    - install_wordpress

- hosts: database
  roles:
    - install_mysql

- hosts: dc
  roles:
    - win_deploy_dc

- hosts: rdp,smb
  roles:
    - win_join_domain
