# Dominic Bonanno
# 12 Sep 2025
# db9063@g.rit.edu
- name: Install Packages # Postfix is as easy-to-use mail service that uses SMTP
  ansible.builtin.apt:
    name:
      - postfix
      - libsasl2-modules
      - logwatch
    state: present
    update_cache: yes
  become: true

- name: Enable Postfix
  ansible.builtin.service:
      name: postfix
      state: started
      enabled: yes 
  become: true
