- name: Copy mail file
  ansible.builtin.copy:
    dest: /etc/mail			#location of file
    content: "smtp example\n"	#content of file
  become: true

- name: Restart postfix
  ansible.builtin.service:
    name: postfix	
    state: restarted		#restart to make sure changes are applied
  become: true
