---
# Author: Masaki
- name: Saving original main.cf just in case
  ansible.builtin.template:
    src: /etc/postfix/main.cf
    dest: /etc/postfix/BAD.cf
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Deploy vulnerable main.cf
  ansible.builtin.template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Enable and restart after config change
  ansible.builtin.service:
    name: postfix
    state: restarted
    enabled: yes
  become: true
