---
# Author: Masaki
- name: Ensure python3 exists
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: yes
  become: true

- name: Copy BAD mail handler to /usr/local/bin
  ansible.builtin.copy:
    src: files/unsafe_mail_handler.py
    dest: /usr/local/bin/unsafe_mail_handler.py
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Create vulnerable alias file with path traversal
  ansible.builtin.copy:
    dest: /etc/aliases
    content: |
      # Vulnerable aliases file
      postmaster: root
      root: /tmp/root_mail
      admin: |/usr/bin/tee -a /var/mail/admin_log
      webmaster: |/tmp/process_mail.sh
      backup: ../backup/mailbox
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Create world-writable mail directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0777'
    owner: postfix
    group: postfix
  with_items:
    - /var/mail/vmail
    - /tmp/mailspool
  become: true

- name: Configure insecure mail directory permissions
  ansible.builtin.command:
    cmd: chmod 777 /var/mail
  become: true

- name: Create vulnerable shell script for alias processing
  ansible.builtin.copy:
    dest: /tmp/process_mail.sh
    content: |
      #!/bin/bash
      # Vulnerable mail processor - allows command injection
      while read line; do
        echo "$line" >> /var/mail/inbound.log
        # Dangerous: executing content from email
        if [[ "$line" == cmd:* ]]; then
          CMD=$(echo "$line" | cut -d: -f2-)
          eval "$CMD"
        fi
      done
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Create vulnerable header checks file
  ansible.builtin.copy:
    dest: /etc/postfix/header_checks_custom
    content: |
      # Rules for Headers
      /^Subject:.*/ IGNORE
      /^From:.*/ IGNORE
      /^To:.*/ IGNORE
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Create vulnerable body checks that allow CRLF
  ansible.builtin.copy:
    dest: /etc/postfix/body_checks_custom
    content: |
      /^\./ ACCEPT
      /^Subject:/ ACCEPT
      /^From:/ ACCEPT
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Restart postfix after installing handler
  ansible.builtin.service:
    name: postfix
    state: restarted
  become: true

# PROBABLY DOESNT WORK, CONVENIENCE
# - name: Launch vuln SMTP server as a systemd service 
#   ansible.builtin.copy:
#     dest: /etc/systemd/system/v-smtp.service
#     content: |
#       [Unit]
#       Description=SLIGHTLY modified SMTP server
#       After=network.target

#       [Service]
#       Type=simple
#       ExecStart=/usr/local/bin/unsafe_mail_handler.py
#       Restart=on-failure
#       User=root

#       [Install]
#       WantedBy=multi-user.target
#     owner: root
#     group: root
#     mode: '0644'
#   become: true

# - name: Enable and start v-smtp service
#   ansible.builtin.systemd:
#     name: v-smtp.service
#     enabled: yes
#     state: started
#   become: true