---
# Author: Masaki
# - name: Saving original main.cf just in case
#   ansible.builtin.copy:
#     src: /etc/postfix/main.cf
#     dest: /etc/postfix/deprecated.cf
#     remote_src: yes
#   become: true

- name: Deploy vulnerable main.cf
  ansible.builtin.template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Enable and restart after config change
  ansible.builtin.service:
    name: postfix
    state: restarted
    enabled: yes
  become: true

- name: Install iptables
  apt:
    name:
      - net-tools
      - iptables-persistent
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Configure firewall to allow SMTP
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 25
    jump: ACCEPT
    comment: "SMTP Server"

- name: Allow Submission (port 587)
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 587
    jump: ACCEPT
    comment: "SMTP Submission, whatever that is"

- name: Save iptables rules
  command: iptables-save --file /etc/iptables/rules.v4
  when: ansible_os_family == "Debian"

- name: Append harmless marker to /etc/postfix/master.cf if absent
  hosts: mailservers
  become: true
  gather_facts: false

- name: Ensure /etc/postfix/master.cf exists
  stat:
    path: /etc/postfix/master.cf
  register: mastercf_stat

- name: Backup master.cf prior to change
  copy:
    src: /etc/postfix/master.cf
    dest: /var/backups/master.cf.{{ ansible_date_time.iso8601 }}
    owner: root
    group: root
    mode: '0600'
  when: mastercf_stat.stat.exists
  become: true

- name: Append safe marker if not present
  ansible.builtin.lineinfile:
    path: /etc/postfix/master.cf
    create: yes
    insertafter: EOF
    line: "# flags=Rq user=admin argv=TROY{INSERT_RSHELL_HERE}-f ${sender} -- ${recipient}"
    state: present
    regexp: '^#\s*TROY\{FLAG_PLACEHOLDER'
    backup: yes
  become: true
  notify:
    - validate postfix
    - reload postfix


